insert into inventory (
    name,
    asset,
    cost
) values
    ('Almond Joy Cookie', 'almond-joy.jpg', 0),
    ('Amish Sugar Cookie', 'amish-sugar-cookie.jpg', 0),
    ('Bakery Style Chocolate Chip Cookie', 'BAKERY-STYLE-CHOCOLATE-CHIP-COOKIES-9.jpg', 0),
    ('Blue Sprinkles Cookie', 'blue-sprinkles.jpg', 0),
    ('Bootylicious Cookie', 'booty-cake.jpg', 0),
    ('Chocolate Chip Cookie', 'choco-chip.jpg', 0),
    ('Chocolate Chip Drip Cookie', 'choco-drip.jpg', 0),
    ('Chocolate Kettle Cookie', 'choco-kettle.jpg', 0),
    ('Chocolate Chip [Gluten Free] Cookie', 'choco-chip-gluten-free.jpg', 0),
    ('Chrome Cookie', 'chrome-cookie.jpg', 0),
    ('Cotton Nerdy Cookie', 'cotton-candy.jpg', 0),
    ('Cowboy Angle Cookie', 'cowboy-angle.jpg', 0),
    ('Dark Double Chocolate Chip Cookie', 'dark-double-trouble.jpg', 0),
    ('Double Chocolate Chip Cookie', 'dark-choco-chip.jpg', 0),
    ('Double Trouble Chocolate Chip Cookie', 'double-choco-2.jpg', 0),
    ('Double Triad Chocolate Chip Cookie', 'double-choco-3.jpg', 0),
    ('Malware Cookie', 'evil-faces.jpg', 0),
    ('Frosted Sugar Cookie with Jimmies', 'frosted-1.jpg', 0),
    ('Frosted Sugar Cookie with Cotton Candy Frosting', 'frosted-2.jpg', 0),
    ('Frosted Sugar Pizza Cookies', 'Fruit-Pizza-Cookies.jpg', 0),
    ('Gingerbread Cookie with Red Gumdrops', 'gingerbread-1.jpg', 0),
    ('Gingerbread Cookie with Stoplight Gumdrops', 'gingerbread-2.jpg', 0),
    ('Gingerbread Cookie without Ticklish Spots', 'gingerbread-3.jpg', 0),
    ('Internet Explorer & Chrome Cookie', 'ie-chrome.jpg', 0),
    ('Infrastructure as Cookie', 'infra-as-cookie.jpg', 0),
    ('Memorial Day Cookie', 'memorial-day.jpg', 0),
    ('Microsoft Windows Cookie', 'microsoft-windows-cookies.jpg', 0),
    ('Multiple Browsers Cookie', 'multi-browsers-1.jpg', 0),
    ('Multiple Browsers Cookified Chrome', 'multi-browsers-2.jpg', 0),
    ('Oatmeal Cookie', 'Oatmeal-MG_4617.jpg', 0),
    ('Snickerdoodle Cookie', 'snickerdoodle-1.jpg', 0),
    ('Sugar Cookie with Blue, Red, and Green Flavor', 'sugar-cookies-10.jpg', 0),
    ('Sugar Cookie with Depression', 'sugar-cookies-20.jpg', 0),
    ('Sugar Cookie without Depression', 'sugar-frosted.jpg', 0),
    ('Vegan Cowboy Cookie', 'vegan-cowboy.jpg', 0);
